leav-solutions/leav-engine

apps/admin-app/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditForm.tsx, apps/core/src/domain/attribute/attributeDomain.spec.ts, apps/core/src/domain/attribute/attributeDomain.ts
https://unisson.aristid.com/browse/LEAV-447
=> Fix deleted attribute still used in forms

apps/core/src/__tests__/e2e/indexationManager/indexation.test.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.spec.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.ts, apps/core/src/infra/elasticsearch/elasticsearchService.ts
=> Add case and accents insensitivity on Fulltext Search

apps/data-studio/src/components/LibraryItemsList/MenuView/MenuView.tsx, apps/data-studio/src/components/LibraryItemsList/ViewPanel/View/View.tsx, apps/data-studio/src/components/LibraryItemsList/ViewPanel/ViewPanel.tsx, apps/data-studio/src/utils/utils.tsx
https://unisson.aristid.com/browse/LEAV-309
=> Keep current params on new view

apps/data-studio/public/locales/en/translations.json, apps/data-studio/public/locales/fr/translations.json, apps/data-studio/src/__mocks__/common/treeElements.ts, apps/data-studio/src/_gqlTypes/TREE_NODE_CHILDREN.ts, apps/data-studio/src/components/Navigation/Navigation.test.tsx, apps/data-studio/src/components/Navigation/NavigationView/Column/DetailNavigation/DetailNavigation.tsx, apps/data-studio/src/components/Navigation/NavigationView/Column/Row/Row.test.tsx, apps/data-studio/src/components/Navigation/NavigationView/Column/Row/Row.tsx, apps/data-studio/src/components/shared/FloatingMenu/FloatingMenu.tsx, apps/data-studio/src/graphQL/queries/trees/getTreeNodeChildren.ts, apps/data-studio/src/hooks/useTreeLibraryAllowedAsChild/useTreeLibraryAllowedAsChild.test.tsx
- Display menu on each element
- Display a warning icon if element is inactive
=> [data-studio] Minor improvement in navigation

apps/admin-app/src/components/versionProfiles/EditVersionProfile/InfoForm/InfoForm.tsx
https://unisson.aristid.com/browse/LEAV-538
=> fix version profiles edit form

apps/data-studio/src/components/Navigation/NavigationView/Column/HeaderColumnNavigation/HeaderColumnNavigationActions/DefaultActions/DefaultActions.tsx
https://unisson.aristid.com/browse/LEAV-554
=> Create directory on tree root

apps/admin-app/src/components/attributes/EditAttribute/EditAttribute.tsx, apps/admin-app/src/components/attributes/EditAttribute/EditAttributeTabs/EditAttributeTabs.tsx, apps/admin-app/src/components/attributes/EditAttribute/EditAttributeTabs/InfosTab/InfosTab.tsx, apps/admin-app/src/components/attributes/EditAttributeModal/EditAttributeModal.tsx, apps/admin-app/src/components/libraries/EditLibrary/EditLibraryTabs/AttributesTab/AttributesTab.tsx
=> [admin] Fixes attribute creation from library

apps/core/src/__tests__/e2e/api/records/records.test.ts, apps/core/src/__tests__/e2e/api/records/searchFilters.test.ts, apps/core/src/__tests__/e2e/indexationManager/indexation.test.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.ts, apps/core/src/domain/record/recordDomain.ts, apps/core/src/domain/tasksManager/tasksManagerDomain.spec.ts, apps/core/src/infra/db/migrations/001-delIndexAnalyzersViews.ts, apps/core/src/infra/indexation/helpers/getSearchQuery.ts, apps/core/src/infra/indexation/indexationService.ts, apps/core/src/infra/record/__snapshots__/recordRepo.spec.ts.snap, apps/core/src/infra/record/recordRepo.ts, apps/data-studio/src/components/RecordEdition/EditRecord/uiElements/LinkField/ValuesAdd/QuickSearch/QuickSearch.tsx, apps/data-studio/src/components/RecordEdition/EditRecord/uiElements/LinkField/ValuesAdd/ValuesAdd.tsx, docker/docker-compose.yml
https://unisson.aristid.com/browse/LEAV-564
=> [Core, Data Studio] fixes search

apps/core/src/domain/library/helpers/deleteAssociatedValues.ts
https://unisson.aristid.com/browse/LEAV-581
=> Fix delete associated values on delete library attribute 

apps/core/package.json, apps/core/src/domain/import/importDomain.ts, yarn.lock
https://unisson.aristid.com/browse/LEAV-583
=> Fix import with more than 50 elements

apps/core/src/domain/import/importDomain.ts, apps/core/src/locales/en/translation.json, apps/core/src/locales/fr/translation.json, apps/data-studio/src/components/Home/LibrariesList/ImportModal/ImportModalDoneStep/ImportModalDoneStep.tsx
Also improve error handling on import
=> Fix error on Excel import

apps/data-studio/src/components/Navigation/NavigationView/Column/HeaderColumnNavigation/HeaderColumnNavigationActions/DefaultActions/DefaultActions.tsx
https://unisson.aristid.com/browse/XSTREAM-68
=> [Data-studio] Fix generate previews at tree root

apps/data-studio/src/components/Navigation/NavigationView/Column/Column.tsx, apps/data-studio/src/components/Navigation/NavigationView/NavigationView.tsx
https://unisson.aristid.com/browse/XSTREAM-69
=> [Data-Studio] Fix selected tree view 

libs/ui/src/components/EditLibraryModal/EditLibrary/EditLibrary.tsx
https://unisson.aristid.com/browse/XSTREAM-35
=> [Data-Studio] Fix edit lib display

apps/data-studio/src/components/LibraryItemsList/LibraryItemsListContent/LibraryItemsListContent.tsx, apps/data-studio/src/hooks/useSearchReducer/_types.ts, apps/data-studio/src/hooks/useSearchReducer/searchReducer.ts
https://unisson.aristid.com/browse/XSTREAM-95
=> [Data-Studio] Fix error display on search 

apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/InfosTab/InfosForm/InfosForm.tsx, apps/admin/src/queries/records/recordsListQuery.ts
https://unisson.aristid.com/browse/XSTREAM-78
=> [Admin] Fix create library form

apps/sync-scan/src/__tests__/e2e/database/test3.ts, apps/sync-scan/src/__tests__/e2e/index.test.ts
https://unisson.aristid.com/browse/XSTREAM-117
=> [Sync-scan] Fix e2e timeout

apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/BreadcrumbNavigator/BreadcrumbNavigator.test.tsx, apps/admin/src/components/trees/SelectTreeNodeModal/SelectTreeNodeModal.test.tsx, apps/admin/src/components/trees/SelectTreeNodeModal/SelectTreeNodeModal.tsx
=> [admin] Fix tests

apps/core/src/interface/server.ts
In order to use cookies to transport the JWT in a cross origin way (external front app), we cannot use the "*" for Access-Control-Allow-Origin Plus, we have to explicitly allow cookies transmission using credentials: true which translates to Access-Control-Allow-Credential: true
cors middleware natively handles the immediate response for 'OPTIONS' request 
cors middleware is removed from /graphql endpoint as it is defined globally
=> Better usage of cors module

docker/DOCKERFILES/PREVIEW_GENERATOR/Dockerfile
Use node v18 instead of v14 for preview-generator during development
=> [preview-generator] Fix build

apps/core/src/domain/filesManager/filesManagerDomain.ts, apps/core/src/domain/form/formDomain.ts, apps/core/src/infra/db/migrations/000-init/index.ts
Fix a few translations where lang was not passed
=> fix(core): lang missing in translation

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
(sort create_at->limit 20->sort whoAmI.label)
=> fix(@leav/ui): apply correct behavior 

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx, yarn.lock
=> fix: update DS version

apps/core/src/infra/db/dbUtils.ts, docker/docker-compose.yml
- Add **non-essential** profile in development docker-compose (We don't use these services by default)
- Clean **core index field** on _dbUtils.cleanup_ 
=> feature(Docker): Add extra host, non-essential profile. feature(Core): Clean core_index on db cleanup.

docker/scripts/start-core.sh
=> fix(Core):Install plugins dependencies on start

.github/workflows/ci.yml, README.md, docker/docker-compose.prod.yml, docker/docker-compose.yml, docker/scripts/start-core.sh
=> chore: improve docker configuration

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx, libs/ui/src/hooks/useDebouncedValue/useDebouncedValue.test.ts, libs/ui/src/hooks/useDebouncedValue/useDebouncedValue.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(record edition): add fulltext search on link field

apps/core/src/__tests__/e2e/api/permissions/treeLibraryPermissions.test.ts, apps/core/src/infra/attributeTypes/attributeAdvancedLinkRepo.spec.ts, apps/core/src/infra/attributeTypes/attributeAdvancedLinkRepo.ts
=> fix(reverse link): fix delete value

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx
=> fix(record edition): fix save on advanced attributes

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx
=> xStream-512 inherit and override on simple input

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts, libs/ui/src/hooks/useDebouncedValue/useDebouncedValue.test.ts, libs/ui/src/hooks/useDebouncedValue/useDebouncedValue.ts
=> fix(createrecord): fix handling of errors on values save

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
=> fix: xstream-416 fix clear button on link atributes not working

apps/core/src/domain/export/exportDomain.ts, apps/core/src/domain/form/helpers/getElementValues.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.spec.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.ts, apps/core/src/domain/record/recordDomain.ts, libs/ui/src/_queries/records/getRecordsFromLibraryQuery.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/AllValuesCount/AllValuesCount.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.test.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/StandardCell/StandardCell.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/typeGuards.test.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/typeGuards.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/types.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/utils.test.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/utils.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
=> fix(@leav/ui): manage display of inherited values in LibraryItemsList

libs/ui/src/components/RecordEdition/EditRecordContent/antdUtils.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/reducers/standardFieldReducer/standardFieldReducer.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldNumeric.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx
=> Adapt Numeric attribute to Design system

apps/core/src/_types/attribute.ts
-   [ ] Design OK
-   [ ] Can be tested by POs
=> Add "required" field to attributes

pull_request_template.md
-   [x] Design OK
-   [x] Can be tested by POs
=> docs(github): definition of mergeable

apps/core/src/_types/endpoint.ts, apps/core/src/_types/express.ts, apps/core/src/_types/extensionPoints.ts, apps/core/src/app/application/applicationApp.ts, apps/core/src/app/auth/authApp.ts, apps/core/src/app/core/filesManagerApp.ts, apps/core/src/app/core/globalSettingsApp.ts, apps/core/src/app/endpoint/endpointApp.spec.ts, apps/core/src/app/endpoint/endpointApp.ts, apps/core/src/app/endpoint/index.ts, apps/core/src/app/graphql/graphqlApp.ts, apps/core/src/app/helpers/index.ts, apps/core/src/app/helpers/validateRequestToken.spec.ts, apps/core/src/app/helpers/validateRequestToken.ts, apps/core/src/interface/server.ts, apps/core/src/pluginsLoader.ts
=> feat(app): allow plugins to expose endpoints

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, yarn.lock
=> feat: update DS version

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts, apps/core/src/utils/helpers/getValuesToDisplay.spec.ts, apps/core/src/utils/helpers/getValuesToDisplay.ts
=> feat(core): fix getRecordIdentity label when inherited

pull_request_template.md
-   [x] Design OK
-   [x] Can be tested by POs
=> docs(PR): improve rendering by remove NBSP

apps/core/src/_types/value.ts
-   [ ] Design OK
-   [ ] Can be tested by POs
=> fix(core): update IStandardValue raw_value type to match value type

apps/core/src/app/application/__tests__/applicationApp.spec.ts, apps/core/src/app/application/applicationApp.ts
-   [ ] Design OK
-   [ ] Can be tested by POs
=> fix(login): fix apps loading when not authenticated

libs/ui/tsconfig.build.json
=> fix(@leav/ui): let builder known we are using Vite

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.test.tsx, yarn.lock
=> feat: update DS Version to 7.1.0@next

apps/core/src/app/core/globalSettingsApp.ts
=> fix(app logo): fix broken image

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/useGetOptionsQuery.tsx
=> fix: fix idCards images not showing in Select MultiValues

apps/core/src/app/core/recordApp/recordApp.ts
=> feat(graphql): ensure property array is always defined

apps/core/src/_types/errors.ts, apps/core/src/interface/helpers/handleGraphqlError.spec.ts, apps/core/src/interface/helpers/handleGraphqlError.ts, apps/core/src/interface/helpers/index.ts, apps/core/src/interface/server.ts
=> fix: improve handling of validation errors

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
=> xstream-652 Replace search count in select instead of total count

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> Bump version to v1.0.0-beta13

apps/portal/jest.config.js, apps/portal/src/__mocks__/styleMock.js, apps/portal/src/components/Applications/ApplicationsList/ApplicationCard/ApplicationCard.css, apps/portal/src/components/Applications/ApplicationsList/ApplicationCard/ApplicationCard.tsx
=> fix: change portal app card to temporary component

apps/core/src/__tests__/mocks/shared.ts, apps/core/src/_types/queryInfos.ts, apps/core/src/app/auth/authApp.ts, apps/core/src/app/core/eventsManagerApp.ts, apps/core/src/app/core/recordApp/recordApp.ts, apps/core/src/app/endpoint/endpointApp.spec.ts, apps/core/src/app/helpers/initQueryContext.ts, apps/core/src/errors/LeavError.ts, apps/core/src/errors/PermissionError.ts, apps/core/src/errors/ValidationError.ts, apps/core/src/errors/guards.ts, apps/core/src/errors/typeguards.ts, apps/core/src/interface/helpers/handleGraphqlError.ts, apps/core/src/interface/server.ts, apps/core/src/utils/utils.spec.ts, apps/core/src/utils/utils.ts, apps/data-studio/src/components/app/ApolloHandler/ApolloHandler.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListContent/LibraryItemsListContent.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/BodyCell/BodyCell.test.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/BodyCell/BodyCell.tsx, libs/ui/src/components/LibraryItemsList/hooks/useSearchReducer/_types.ts, libs/ui/src/components/LibraryItemsList/hooks/useSearchReducer/searchReducer.ts
=> feat(data-studio, core): Handle errors on search gracefully

apps/core/src/infra/db/_constants.ts, libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/shared/ValueDetailsBtn/useValueDetailsButton.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/useGetOptionsQuery.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/useGetOptionsQuery.tsx
=> Edit multivalues attribute on blur + Validation

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
=> fix bug in mutli select: elements are not added and removed correctly

apps/core/src/errors/typeguards.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/EditRecordModalContext.tsx, libs/ui/src/components/LibraryItemsList/hooks/useSearchReducer/_types.ts, libs/ui/src/components/LibraryItemsList/hooks/useSearchReducer/searchReducer.ts
=> chore: add licence header

apps/core/jest-unit-config.json, apps/core/src/__tests__/global-setup.ts, apps/core/src/domain/actions/formatDateAction.spec.ts
=> test(core): add two about params priority and auto param

README.md, apps/core/src/__tests__/e2e/api/e2eUtils.ts, apps/core/src/__tests__/jestUtils.ts, apps/core/src/__tests__/mocks/actionsList.ts, apps/core/src/_types/actionsList.ts, apps/core/src/_types/attribute.ts, apps/core/src/domain/actions/excelCalculationAction.spec.ts, apps/core/src/domain/actions/excelCalculationAction.ts, apps/core/src/domain/actions/formatDateAction.spec.ts, apps/core/src/domain/actions/formatDateAction.ts, apps/core/src/domain/actions/formatDateRangeAction.spec.ts, apps/core/src/domain/actions/formatDateRangeAction.ts, apps/core/src/domain/actions/formatNumberAction.spec.ts, apps/core/src/domain/actions/formatNumberAction.ts, apps/core/src/domain/actions/inheritanceCalculationAction.spec.ts, apps/core/src/domain/actions/inheritanceCalculationAction.ts, apps/core/src/domain/actions/validateFormatAction.ts, apps/core/src/domain/actions/validateRegexAction.ts, apps/core/src/domain/actionsList/actionsListDomain.ts, apps/core/src/domain/attribute/helpers/attributeALHelper.ts, apps/core/src/domain/value/valueDomain.spec.ts, apps/core/src/infra/db/dbService.spec.ts, apps/core/src/utils/helpers/getDefaultActionsList.ts, apps/core/src/utils/utils.ts
=> feat(core): improve typescript for safety

apps/core/src/domain/actions/formatDateAction.ts, apps/core/src/domain/actions/formatDateRangeAction.spec.ts, apps/core/src/domain/actions/formatDateRangeAction.ts
=> feat(core): copy action params to unify actions on dates

apps/admin/jest.config.js, apps/admin/src/hooks/useAuth/useAuth.ts, apps/admin/src/hooks/useRefreshToken/types.d.ts, apps/admin/src/hooks/useRefreshToken/useRefreshToken.ts, apps/core/src/__tests__/e2e/api/auth/auth.test.ts, apps/core/src/_types/utils.ts, apps/core/src/app/auth/__tests__/authApp.spec.ts, apps/core/src/app/auth/authApp.ts, apps/login/src/components/Login/Login.test.tsx, apps/login/src/components/Login/Login.tsx, apps/login/src/hooks/useAuthChecker/useAuthChecker.test.ts, libs/ui/package.json, libs/ui/src/hooks/useAuth/useAuth.test.ts, libs/ui/src/hooks/useAuth/useAuth.ts, libs/ui/src/hooks/useRefreshToken/useRefreshToken.test.ts, libs/ui/src/hooks/useRefreshToken/useRefreshToken.ts, tsconfig.json
=> feat: manage refresh token for local

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/ElementsReserve/AttributesList/ReserveAttribute/ReserveAttribute.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/uiElements/index.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/helpers/extractFormElements/extractFormElements.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/helpers/extractFormElements/extractFormElements.tsx, libs/utils/src/types/forms.ts
=> feat: add useAttributeLabel option in forms attributes

libs/ui/package.json, yarn.lock
=> chore(@leav/ui): set aristid-ds as dev and peer dependency to avoid nodes_module duplication

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, apps/portal/src/components/Applications/Applications.tsx, apps/portal/src/components/Applications/EditApplicationModal/EditApplicationModal.tsx, libs/ui/package.json, libs/ui/src/antdTheme/index.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/BodyCell/BodyCell.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, yarn.lock
=> fix: upgrade aristid-ds version so it match the one required by @leav/ui peerdependencies

apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/formBuilderReducer/computeInitialState.ts
=> fix: fix not working case

docker/docker-compose.prod.yml, docker/docker-compose.yml
=> chore: update docker-compose to use healthcheck instead of wait-for-it script

apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCCard/ActionContent/Param/Param.tsx, apps/core/src/__tests__/e2e/api/values/values.test.ts, apps/core/src/domain/actions/formatDateAction.spec.ts, apps/core/src/domain/actions/formatDateAction.ts, apps/core/src/domain/actions/formatDateRangeAction.spec.ts, apps/core/src/domain/actions/formatDateRangeAction.ts
=> feat(core): allow options for action date & date range

libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/StandardCell/StandardCell.tsx
=> Fix boolean on library items list

docker/DOCKERFILES/build/core.Dockerfile, docker/scripts/plugins_install.sh
https://aristid.atlassian.net/browse/XSTREAM-602
=> Install plugins modules on build

apps/core/src/config.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.spec.ts, apps/core/src/domain/indexationManager/indexationManagerDomain.ts, apps/core/src/index.ts, docker/docker-compose.yml
=> fix(core): invalid import and conf validation

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> Bump version to v1.0.0-beta14

apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/formBuilderReducer/helpers/actions/saveSettings.ts, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/uiElements/layout/Tabs/Tabs.tsx
=> fix: fix forms tabs

libs/ui/src/components/ImportModal/ImportModalSelectFileStep/ImportModalSelectFileStep.tsx
=> fix(import): empty first line

.github/workflows/ci.yml, docker/docker-compose.prod.yml, docker/docker-compose.yml
=> chore: upgrade arangodb version

libs/ui/src/components/RecordEdition/EditRecordContent/antdUtils.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSBooleanWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSBooleanWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx, libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx
=> feat(leav-ui): adapat boolean to design system

apps/core/src/infra/db/helpers/runMigrationFiles.ts, apps/core/src/infra/db/migrations/002-previewsSettings.ts
J'ajoute un fichier de test:
Ce fichier est bien sauvegardé sans son extension
Si je modifie son extension:
Celle-ci n'est pas prise en compte et le script n'est pas rejoué (on peut constaté que le script `002-previewSettings.ts` ne génère plus d'erreurs)
```
<Title>
```
-   [ ] Design …
=> fix(core): add some check so 002-previewsSetting migration script can be run multiple times and don't check file extension on migration scanner

apps/automate-scan/tsconfig.build.json, apps/core/tsconfig.build.json, apps/logs-collector/tsconfig.build.json, apps/sync-scan/tsconfig.build.json
=> xstream-595 typescript 5 migration + eslint 8

apps/core/README.md, apps/core/config/default.js, apps/core/src/_types/config.ts, apps/core/src/config.ts, apps/core/src/depsManager.ts, docker/scripts/start-core.sh
=> feat(core): make plugins path configurable

docker/scripts/plugins_install.sh
=> chore(core): fix plugins install on docker image

apps/core/src/depsManager.ts, apps/core/src/pluginsLoader.ts
=> fix(core): handle invalid plugins path

apps/core/package.json, test-apps/logs/package.json, yarn.lock
Fixes the following security alerts:
- https://github.com/leav-solutions/leav-engine/security/dependabot/120
- https://github.com/leav-solutions/leav-engine/security/dependabot/116
- https://github.com/leav-solutions/leav-engine/security/dependabot/110
```
<Title>
``` …
=> SecurityFixes

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, yarn.lock
=> chore: update aristid ds version

apps/core/src/app/core/recordApp/_types.ts, apps/core/src/app/core/recordApp/recordApp.ts, apps/core/src/domain/record/recordDomain.ts
=> fix(core): fix create record

apps/core/src/interface/helpers/handleGraphqlError.ts
=> feat(core): add uid to handleGraphqlErrpr returned object

apps/core/src/domain/import/import-data-schema.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValueDisplayHandler/StandardFieldValueRead/StandardFieldValueRead.tsx
=> chore: update json schema

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, yarn.lock
=> fix: update ds versin

libs/ui/codegen.ts, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/explorerQuery.graphql, libs/ui/src/components/Explorer/tsconfig.json, libs/ui/src/components/Explorer/types.ts, libs/ui/src/components/Explorer/useExplorerData.ts
=> feat(@leav/ui): init an api call to get data

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/types.ts, libs/ui/src/components/Explorer/useExplorerData.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(@leav/ui): add actions on item

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/types.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
copy and paste from DeactivateRecordBtn.tsx
```
<Title>
```
=> feat(@leav/ui): add logic about deactivated item

apps/core/src/app/core/exportApp.ts, apps/core/src/domain/export/exportDomain.spec.ts, apps/core/src/domain/export/exportDomain.ts
=> Export data function

apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/EmbeddedFieldsTab/EmbeddedFieldsTab.tsx, apps/core/src/domain/export/exportDomain.spec.ts
=> Fix admin embedded field form

apps/core/src/infra/attributeTypes/attributeAdvancedRepo.spec.ts, apps/core/src/infra/attributeTypes/attributeAdvancedRepo.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValueDisplayHandler/StandardFieldValueDisplayHandler.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValueDisplayHandler/StandardFieldValueRead/StandardFieldValueRead.tsx
=> fix(@leav/ui): value disappearing on blur on advanced field

apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/formBuilderReducer/helpers/actions/saveSettings.ts
=> Fix missing element's setting form compared to action settings

libs/ui/src/_utils/index.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx
=> fix(@leav/ui): set date on date picker and range picker to noon

apps/core/src/__tests__/e2e/api/values/values.test.ts, apps/core/src/_types/value.ts, apps/core/src/app/core/valueApp.ts, apps/core/src/domain/value/valueDomain.spec.ts, apps/core/src/domain/value/valueDomain.ts, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/_queries/values/getValueAfterActionsListAndFormatQuery.graphql, libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/hooks/useRunActionsListAndFormatOnValue.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/hooks/useRunActionsListAndFormatOnValue.ts
=> feat: add a query to run actions list and format on a given value and use it in @leav/ui

libs/ui/src/components/RecordEdition/EditRecordContent/reducers/standardFieldReducer/standardFieldReducer.ts
=> fix(leav/ui): override value undefined

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/MonoValueSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/MonoValueSelect.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(leav/ui): opened values list selection

apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ValuesListTab/ValuesListForm/ValuesListForm.tsx
=> fix(admin): multiple value meca switches

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/ExplorerTitle.tsx, libs/ui/src/components/Explorer/_queries/libraryDataQuery.graphql, libs/ui/src/components/Explorer/useEditAction.tsx
=> Explorer title

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx
=> fix(leav/ui): payload value

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/_queries/explorerQuery.graphql
=> feat(explorer): display value properly for simple cases

libs/ui/src/components/Explorer/TableCell.tsx
=> feat(@leav/ui): explorer display Boolean values

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/IdCard.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts
=> feat(explorer): handle link attributes in table

apps/core/src/app/core/recordApp/recordApp.ts, libs/ui/src/__mocks__/common/record.ts, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/_queries/explorerQuery.graphql, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts
=> fix(explorer): header label if no values

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/_types.ts
=> [Explorer] Multival links

apps/core/src/domain/value/helpers/findValue.ts, apps/core/src/domain/value/valueDomain.spec.ts, apps/core/src/domain/value/valueDomain.ts
=> fix(core): getValues with versions on empty tree

.github/workflows/build_develop.yml, .github/workflows/publish.yml
=> AMP-171 Adding arm support for develop images

apps/core/src/_types/endpoint.ts, apps/core/src/app/endpoint/endpointApp.spec.ts, apps/core/src/app/endpoint/endpointApp.ts
With great power comes great responsibility
```
<Title>
```
=> feat(core): plugins can register an unprotected route

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/TableTagGroup.tsx
=> feat(@leav/ui): display summary for rich text

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSBooleanWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSBooleanWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSColorPickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputEncryptedWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRichTextWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/MonoValueSelect.tsx
=> fix(leav/ui): focus field on click on label

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx
=> feat(@leav/ui): display color block and hexa code

.github/workflows/build_develop.yml, apps/core/README.md, apps/core/package.json, docker/DOCKERFILES/build/core.Dockerfile, docker/DOCKERFILES/build/core.dev.Dockerfile
=> AMP-170 Adding hot reload on dev core image

docker/DOCKERFILES/build/core.Dockerfile, docker/DOCKERFILES/build/core.dev.Dockerfile
=> fix assets in docker image

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_queries/explorerQuery.graphql, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsInitialState.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts, libs/ui/src/components/Explorer/useSearchInput.tsx
=> feat(explorer): fulltext search

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/Explorer/TableTagGroup.tsx
=> feat(@leav/ui): manage display multi color attribute

apps/data-studio/src/components/app/AppHandler/AppHandler.tsx, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/CreateDirectory/CreateDirectory.tsx, libs/ui/src/components/LibraryItemsList/FiltersPanel/Filter/Filter.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/TreeField/ValuesAdd/ValuesAdd.tsx, libs/ui/src/components/SelectTreeNode/SelectTreeNode.test.tsx, libs/ui/src/components/SelectTreeNode/SelectTreeNode.tsx, libs/ui/src/components/SelectTreeNode/SelectTreeNodeContent.tsx, libs/ui/src/components/SelectTreeNode/_queries/treeDataQuery.graphql, libs/ui/src/components/SelectTreeNode/index.ts, libs/ui/src/components/SelectTreeNodeModal/SelectTreeNodeModal.test.tsx, libs/ui/src/components/SelectTreeNodeModal/SelectTreeNodeModal.tsx, libs/ui/src/components/SelectTreeNodeModal/index.ts, libs/ui/src/components/UploadFiles/UploadFiles.tsx, libs/ui/src/components/ValuesVersionConfigurator/ValuesVersionConfigurator.test.tsx, libs/ui/src/components/ValuesVersionConfigurator/VersionTree/VersionTree.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> Tree modal

libs/ui/src/components/Explorer/manage-view-settings/_shared/ColumnItem.tsx, libs/ui/src/components/Explorer/manage-view-settings/configure-display/attributes/SelectVisibleAttributes.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> fix(explorer): cosmetic fixes on display mode settings

apps/core/config/default.js, apps/core/src/_types/config.ts, apps/core/src/config.ts, apps/core/src/domain/apiKey/apiKeyDomain.spec.ts, apps/core/src/domain/apiKey/apiKeyDomain.ts, apps/core/src/index.ts, docker/docker-compose.yml
=> feat(api keys): add a configurable test api key

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(exploer) handle date range attribute

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/display-view-filters/ExplorerFilterBar.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterValueList.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/NumericAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/SimpleFilterDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/TextAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/useConditionOptionsByType.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(@leav/ui): explorer text and rich text filter

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/DSListSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/DSListSelect.tsx
=> fix(leav/ui): remove selected options from multiple select

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, yarn.lock
=> fix(leav/ui): recette

libs/ui/src/components/Explorer/display-view-filters/ExplorerFilterBar.tsx, libs/ui/src/components/Explorer/manage-view-settings/_shared/CommonFilterItem.test.tsx, libs/ui/src/components/Explorer/manage-view-settings/_shared/CommonFilterItem.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterListItem.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/NumericAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/TextAttributeDropDown.tsx
=> feat(@leav/ui): refactor filters for testing

libs/types/package.json, yarn.lock
=> fix(@aristid/leav-types): add missing types

libs/types/package.json, yarn.lock
=> chore(@aristid/leav-types): change dependencies

libs/types/package.json, yarn.lock
=> fix(@aristid/leav-types): must work outside project

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/antdUtils.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSColorPickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRichTextWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/StandardFieldValue.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/DSListSelect.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/_types.ts, yarn.lock
=> feat(@leav/ui): add auto focus/blur when adding a new value for multivalues attributes

libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/NumericAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/SimpleFilterDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/TextAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
=> fix(@leav/ui): allow to reset filter condition + value

apps/admin/src/queries/attributes/getAttributesQuery.ts
=> fix(admin): attributes list

apps/core/src/domain/attribute/attributeDomain.ts
=> fix(core): fix doesCompute function on empty actions list

libs/ui/src/_utils/interleaveElement.test.ts, libs/ui/src/_utils/interleaveElement.ts, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/_shared/CommonFilterItem.test.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/DateAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/useConditionOptionsByType.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx
=> feat(@leav/ui): add date format filter

libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
=> feat(explorer): allow filters on link attributes

libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/DateAttributeDropDown.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/useConditionOptionsByType.ts, libs/ui/src/components/Explorer/nullValuesConditions.ts
=> fix(@leav/ui): fix date filter not working options

apps/core/src/__tests__/e2e/api/views/views.test.ts, apps/core/src/__tests__/mocks/view.ts, apps/core/src/_types/views.ts, apps/core/src/app/core/viewApp.ts, apps/core/src/infra/db/migrations/000-init/index.ts, apps/core/src/infra/view/__snapshots__/viewRepo.spec.ts.snap, apps/data-studio/src/graphQL/queries/libraries/getLibraryDetailExtendQuery.ts, libs/ui/src/__mocks__/common/view.ts, libs/ui/src/__mocks__/mockQuery/mockGetLibraryDetailExtendedQuery.ts, libs/ui/src/__mocks__/mockQuery/mockGetViewListQuery.ts, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/_queries/libraries/getLibraryDetailExtendQuery.ts, libs/ui/src/_queries/views/viewDetailsFragment.ts, libs/ui/src/_utils/index.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListContent/LibraryItemsListContent.tsx, libs/ui/src/components/LibraryItemsList/MenuView/MenuView.tsx, libs/ui/src/components/LibraryItemsList/ViewPanel/EditView/EditView.tsx, libs/ui/src/components/LibraryItemsList/ViewPanel/ViewPanel.test.tsx, libs/ui/src/components/LibraryItemsList/helpers/getFieldsFromView.ts, libs/ui/src/components/LibraryItemsList/hooks/useLibraryView/useLibraryView.tsx, libs/ui/src/components/LibraryItemsList/hooks/useSearchReducer/searchReducer.ts, libs/ui/src/types/views.ts
Attributes were previously stored in settings.fields
```
<Title>
```
=> feat(core, @leav/ui): add attributes on all views

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.tsx
=> feat(@leav/ui): add prop to render edit record sidebar inside a given container

apps/core/src/app/application/applicationApp.ts, apps/core/src/errors/ApplicationError.ts, apps/core/src/errors/LeavError.ts, apps/portal/src/locales/en/translations.json, apps/portal/src/locales/fr/translations.json
=> feat(core): check permissions before serving app

libs/ui/src/components/Explorer/_queries/useExplorerData.ts
=> fix(@leav/ui): bug in date filter on not equal condition

libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx
=> fix(ui): only reload fields of curent record

libs/types/package.json, yarn.lock
=> feat(leav-types): add types for AMP

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.tsx
=> feat(@leav/ui): use SidePanel from DS and update edit record modal render

libs/ui/src/components/Explorer/useViewSettingsReducer.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Header/Header.tsx
=> fix(explorer): loading views with columns only

libs/ui/src/_queries/records/getRecordColumnsValues.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/ComputeIndicator.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/PropertiesList/PropertiesList.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/PropertiesList/PropertiesList.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordInformations/RecordInformations.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordInformations/RecordInformations.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordInformations/useRecordInformations.test.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordInformations/useRecordInformations.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordSummary.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordSummary.tsx, libs/ui/src/constants.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(@leav/ui): improve and adapt to the design system the form record summary

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, apps/data-studio/src/components/Sidebar/Sidebar.tsx, apps/data-studio/src/locales/en/translations.json, apps/data-studio/src/locales/fr/translations.json, apps/data-studio/src/utils/utils.tsx, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/ExplorerTitle.tsx, libs/ui/src/components/Explorer/_queries/attributesDataQuery.graphql, libs/ui/src/components/Explorer/_queries/explorerQuery.graphql, libs/ui/src/components/Explorer/_queries/libraryDataQuery.graphql, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/manage-view-settings/manage-view-settings.test.tsx, libs/ui/src/components/Explorer/manage-view-settings/router-menu/SettingsPanel.tsx, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsInitialState.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts, libs/ui/src/components/Explorer/useEditAction.tsx, libs/ui/src/components/Explorer/useSearchInput.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts
=> feat(explorer): handle links

libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/_shared/CommonFilterItem.test.tsx, libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/BooleanAttributeDropdown.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(@leav/ui): [explorer] update boolean filter

apps/data-studio/src/components/TopBar/UserMenu/UserMenu.tsx, apps/data-studio/src/components/app/AppHandler/AppHandler.tsx, apps/login/src/components/ContentWrapper/ContentWrapper.tsx, apps/portal/src/components/App/App.tsx, apps/portal/src/components/Applications/Applications.tsx, apps/portal/src/components/Applications/EditApplicationModal/EditApplicationModal.tsx, libs/ui/src/antdTheme/index.ts
=> style: restore DS default primary color

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_queries/attributesDataQuery.graphql, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/useCreateAction.tsx, libs/ui/src/components/Explorer/usePrimaryActions.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts, libs/ui/src/components/RecordEdition/EditRecordContent/_types.ts
=> feat(explorer): create and link a new record to link attribute

apps/core/src/__tests__/mocks/view.ts, apps/core/src/_types/views.ts, apps/core/src/app/core/viewApp.ts, apps/core/src/domain/view/viewDomain.ts, apps/core/src/infra/db/migrations/000-init/index.ts, apps/core/src/infra/view/_types.ts, apps/core/src/infra/view/viewRepo.spec.ts, apps/core/src/infra/view/viewRepo.ts
=> fix(core): remove declare global for Iview types

apps/core/README.md
=> docs(core): update docs about debugging

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx
=> feat(@leav/ui): allow a custom empty message on `<Explorer />`

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSkeleton/EditRecordSkeleton.tsx, libs/ui/src/components/RecordEdition/EditRecordSkeleton/index.ts, libs/ui/src/components/RecordEdition/index.ts
=> feat(@leav/ui): export EditRecordSkeleton component

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableCell.tsx
=> feat(explorer): display false as default value for boolean attributes

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/ComputeIndicator.tsx
=> feat(@leav/ui): remove distinction between calculated and inheriated for compute indicator tooltip

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/useColumnWidth.tsx
=> feat(explorer): fix table display with many columns

apps/core/src/infra/attributeTypes/helpers/getConditionPart.ts, apps/core/src/infra/record/recordRepo.ts, apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/_queries/prepareFiltersForRequest.ts
=> feat(@leav/ui): filter on date is empty and 'is not empty' returns all records

apps/core/src/domain/export/exportDomain.ts
=> fix(@core): export to excel not working

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/Explorer.tsx
=> fix(explorer): cosmetic on empty lists

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/_gqlTypes/GET_GLOBAL_SETTINGS.ts, apps/admin/src/components/general/General/GeneralCustomizationTab/CustomizationForm/CustomizationForm.tsx, apps/admin/src/components/general/General/GeneralCustomizationTab/GeneralCustomizationTab.test.tsx, apps/admin/src/queries/globalSettings/getGlobalSettingsQuery.ts, apps/admin/src/queries/globalSettings/saveGlobalSettingsMutation.ts, apps/core/src/__tests__/mocks/globalSettings.ts, apps/core/src/_constants/globalSettings.ts, apps/core/src/_types/globalSettings.ts, apps/core/src/app/application/__tests__/applicationApp.spec.ts, apps/core/src/app/application/applicationApp.ts, apps/core/src/app/core/globalSettingsApp.ts, apps/core/src/domain/globalSettings/globalSettingsDomain.ts, apps/core/src/infra/globalSettings/__snapshots__/globalSettingsRepo.spec.ts.snap, apps/core/src/infra/globalSettings/globalSettingsRepo.ts
=> AMP-198 Adding default application choice in leav admin

libs/ui/src/components/RecordEdition/EditRecordSidebar/AttributeSummary/AttributeSummary.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/AttributeSummary/index.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/AttributeSummary/useAttributeInformations.test.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/AttributeSummary/useAttributeInformations.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/Breacrumb/Breadcrumb.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/Breacrumb/Breadcrumb.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/Breacrumb/index.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(leav/ui): add attribute side panel and breadcrumb

libs/ui/src/components/Explorer/Explorer.test.tsx
=> test(@leav/ui): increase timeout in hope of solving flaky test

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/_queries/useExplorerData.ts
=> feat(explorer): Subscription to handle refresh when Editing

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx, libs/ui/src/components/SelectTreeNode/SelectTreeNode.test.tsx, yarn.lock
=> fix(@leav/ui): fix RangePicker render to display only one input with the presentation value

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts
=> Fix(core): Values errors type on record creation

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/_types.ts, libs/ui/src/components/RecordEdition/EditRecordContent/hooks/useCreateRecordMutation.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.integration.test.tsx
=> fix(leav/ui): multiple input required in error

libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/link-item/LinkModal.tsx, libs/ui/src/components/Explorer/link-item/useLinkMassAction.test.tsx, libs/ui/src/components/Explorer/link-item/useLinkMassAction.tsx
=> fix(explorer): close modal when linking existing element

libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, libs/ui/src/hooks/useGetRecordValuesQuery/useGetRecordValuesQuery.ts
=> fix(@leav/ui): stop query record values on edit record content

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRichTextWrapper.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(@leav/ui): keep showCount always displayed for simple and rich text

apps/core/src/domain/record/recordDomain.ts, docker/docker-compose.yml
=> fix(core): Fix _getPreviews func (filePreviewsValue check) and docker preview-generator service stard cmd

libs/ui/src/components/Explorer/manage-view-settings/open-view-settings/EditSettingsContextProvider.tsx
=> fix(leav/ui): edit settings provider type

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRichTextWrapper.tsx
=> fix(@leav/ui): if character limit is null set showCount to undefined

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.tsx
=> fix(@leav/ui): hide duplicate date of rangepicker

libs/ui/src/_utils/index.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSDatePickerWrapper.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSRangePickerWrapper.test.tsx
=> fix(@leav/ui): fix setDateToUTCNoon function to no longer shift the date by one month

apps/data-studio/src/locales/en/translations.json, apps/data-studio/src/locales/fr/translations.json, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordSummary.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordSummary.tsx
=> feat(leav/ui): add loading and error states to record summary in sidebar

libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/actions-primary/usePrimaryActions.tsx, libs/ui/src/components/Explorer/manage-view-settings/open-view-settings/useOpenViewSettings.tsx, libs/ui/src/components/Explorer/useSearchInput.tsx
=> feat(explorer): update elements display order

apps/core/package.json, docker/DOCKERFILES/build/core.Dockerfile, docker/DOCKERFILES/build/core.dev.Dockerfile, yarn.lock
=> fix(core): move dependencies installation in runner img core dockerfiles

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/_queries/meQuery.graphql, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/manage-view-settings/manage-view-settings.test.tsx, libs/ui/src/components/Explorer/manage-view-settings/save-view/SaveViewModal.tsx, libs/ui/src/components/Explorer/manage-view-settings/save-view/ViewActionsButtons.tsx, libs/ui/src/components/Explorer/manage-view-settings/save-view/useCreateNewView.tsx, libs/ui/src/components/Explorer/manage-view-settings/save-view/useShareView.tsx, libs/ui/src/components/Explorer/manage-view-settings/save-view/useUpdateView.tsx, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts, libs/ui/src/components/Explorer/useLoadView.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(explorer): share view + required field save view at first

apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/ExplorerToolbar.tsx, libs/ui/src/components/Explorer/TableCell.tsx
=> feat(explorer): parameterize explorer parts visibility. also expose primary actions as a ref

apps/data-studio/src/locales/en/translations.json, apps/data-studio/src/locales/fr/translations.json, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/useGetPresentationValues.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/ValuesSummary/ValuesSummary.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/ValuesSummary/ValuesSummary.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> Fix trads, case without back value, display period as strings in sidebar

libs/ui/src/components/SelectTreeNode/SelectTreeNodeContent.tsx
=> fix(data-studio): could not select directories in tree when creating a file or a directory

apps/core/config/default.js, apps/core/src/_types/config.ts, apps/core/src/app/auth/__tests__/authApp.spec.ts, apps/core/src/app/auth/authApp.ts, apps/core/src/config.ts, apps/core/src/infra/oidc/oidcClientService.ts
=> AMP-204 Skipping keycloak logout confirmation page

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> Release beta17 - develop

apps/core/src/domain/actions/excelCalculationAction.ts, apps/core/src/domain/helpers/calculationVariable/index.ts, apps/core/src/domain/helpers/calculationsVariableFunctions/calculationsVariableFunctions.spec.ts, apps/core/src/domain/helpers/calculationsVariableFunctions/index.ts
=> fix(core): tree attribute on getValue calculation variable function + raw payload on from/toDate calc funcs

apps/core/src/domain/import/importDomain.ts
=> fix(core): import excel (rename value to payload)

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/actions-item/useEditItemAction.tsx, libs/ui/src/components/Explorer/actions-primary/useCreatePrimaryAction.tsx, libs/ui/src/components/RecordEdition/EditRecord/EditRecord.test.tsx, libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.test.tsx, libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.test.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx
=> feat(leav/ui): allow to specify formId for edition and creation

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx
=> fix(explorer): hide pagination when noPagination={true}

.github/workflows/publish-ui-next.yml, .github/workflows/publish-ui.yml, libs/ui/package.json
=> ci(@leav/ui): add script to publish npm version

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_queries/prepareFiltersForRequest.ts, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/actions-mass/useDeleteLinkValues.tsx, libs/ui/src/components/Explorer/actions-mass/useMassActions.tsx, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsInitialState.ts, libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts, libs/ui/src/components/Explorer/useViewSettingsReducer.ts
=> feat(explorer): allow to use Filters with OR operator instead of AND by default

libs/ui/package.json, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, yarn.lock
=> fix: libs utils version in leav/ui

docker/docker-compose.yml
=> fix(core): redis service healthcheck

libs/ui/package.json, libs/utils/package.json, yarn.lock
=> chore(leav/utils): new version

.github/workflows/build_develop.yml
=> ci(build): do not cancel old job on building develop docker images

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/Frame/Frame.tsx
=> feat(data-studio): handle iframe form communication

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts
=> feat(core): check permission when getting recordFieldValue

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/actions-mass/useDeactivateMassAction.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat(explorer): manage delete permission for mass deactivvation

libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/_queries/attributesByLibWithPermissions.graphql, libs/ui/src/components/Explorer/_queries/attributesDataQuery.graphql, libs/ui/src/components/Explorer/_queries/libraryAttributesQuery.graphql, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/manage-view-settings/_shared/useAttributeDetailsData.tsx, libs/ui/src/components/Explorer/manage-view-settings/_shared/useTransformFilters.tsx, libs/ui/src/components/Explorer/manage-view-settings/manage-view-settings.test.tsx, libs/ui/src/components/Explorer/useLoadView.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts
=> feat(explorer): do not show attributes with no access permission

apps/core/src/domain/record/recordDomain.spec.ts, apps/core/src/domain/record/recordDomain.ts, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_queries/attributesDataQuery.graphql, libs/ui/src/components/Explorer/_queries/explorerQuery.graphql, libs/ui/src/components/Explorer/_queries/useExplorerData.ts, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/actions-item/useRemoveItemAction.tsx, libs/ui/src/components/Explorer/actions-item/useReplaceItemAction.tsx, libs/ui/src/components/Explorer/actions-mass/useDeleteLinkValues.tsx, libs/ui/src/components/Explorer/actions-primary/useCreatePrimaryAction.tsx, libs/ui/src/components/Explorer/actions-primary/useLinkPrimaryAction.tsx, libs/ui/src/components/Explorer/manage-view-settings/_shared/useTransformFilters.tsx
=> handle delete Permissions for items

libs/ui/src/components/Explorer/IdCard.tsx
=> fix(explorer): remove libraryId as sublabel when sublabel not available

apps/core/src/_types/value.ts, apps/core/src/app/core/valueApp.ts, apps/core/src/domain/actionsList/actionsListDomain.spec.ts, apps/core/src/domain/actionsList/actionsListDomain.ts, apps/core/src/domain/value/helpers/isEmptyValue.ts, apps/core/src/domain/value/helpers/prepareValue.ts, apps/core/src/infra/value/valueRepo.ts
=> feature(core): Add empty value as possible payload on standard attributes

libs/ui/src/components/Explorer/actions-mass/useDeleteLinkValues.tsx
=> fix(explorer): deleteLinkValueAction do not use the correct datas

libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/typeGuards.test.ts, libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/typeGuards.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/ValuesSummary/ValuesSummary.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/ValuesSummary/ValuesSummary.tsx, libs/ui/src/components/RecordEdition/editRecordReducer/editRecordReducer.ts
=> fix(@leav/ui): handle tree, link and boolean properly in record sidebar

.github/workflows/ci.yml, apps/data-studio/src/components/LibraryHome/LibraryHome.tsx, apps/login/src/components/ForgotPassword/ForgotPassword.test.tsx, apps/login/src/components/Login/Login.test.tsx, libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/TableTagGroup.tsx
=> feat(explorer): FLAKY LOGIN TESTS : temporary fix + ux evolve on explorer + remove test buttons

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/actions-item/useReplaceItemAction.tsx, libs/ui/src/components/Explorer/actions-primary/useLinkPrimaryAction.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/action-primary/useRecordSelector.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-creation/useLinkRecordsInCreation.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-edition/useLinkRecords.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-edition/useLinkRecords.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-edition/useLinkRecordsInEdition.tsx, libs/ui/src/components/SelectRecordForLinkModal/SelectRecordForLinkModal.tsx
=> feat: multiples fixes

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> Release beta19 - dev

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx, libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx, libs/ui/src/components/RecordEdition/hooks/useGetSubmitButtons.test.tsx, libs/ui/src/components/RecordEdition/hooks/useGetSubmitButtons.tsx
=> fix(@leav/ui): record not created from creation modal when opened from another modal

libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/EditRecordSidebar.tsx
=> fix(leav/ui): sidebar title when attribute is focused

libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx
=> fix(@leav/ui): error are now correctly displayed even with layout elements in form

libs/ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx, libs/ui/src/components/ErrorBoundary/ErrorBoundaryContent/ErrorBoundaryContent.tsx, libs/ui/src/components/SimpleErrorBoundary/SimpleErrorBoundary.test.tsx, libs/ui/src/components/SimpleErrorBoundary/SimpleErrorBoundaryContent/SimpleErrorBoundaryContent.tsx
=> feat(@leav/ui): hide details error on prod build

libs/ui/package.json, yarn.lock
*moove react router to peer dependencies to prevent using multi version and fix inexpected router errors
=> fix(@leav/ui): erreur de formulaire ticket amp265

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> Release beta20 - dev

.github/workflows/ci.yml, apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, libs/ui/package.json, yarn.lock
=> Fix/LEAVC - 57 - update DS in leav for TagGroup fix

libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx
=> feat(@leav/ui): make EditRecordPage header hiddeable (visible by default)

libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsInitialState.ts
=> feat(explorer): remove 100 items pageSize option

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/useColumnWidth.tsx
=> fix(explorer): set minimum width for action header

libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/useViewSettingsReducer.ts
=> feat(explorer): allow to ignore last view settings when no defaultViewSettingsDefined in explorer

libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-edition/useLinkRecordsInEdition.tsx
=> fix(form): able to delete monovalued field not required

apps/admin/src/_gqlTypes/globalTypes.ts, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/CustomConfigTab/CustomConfigTab.test.tsx, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/CustomConfigTab/index.ts, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/EditAttributeTabs.test.tsx, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/EditAttributeTabs.tsx, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/MetadataTab/MetadataList/MetadataList.test.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/AttributesTab/AttributesTab.test.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/CustomConfigTab/CustomConfigTab.test.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/CustomConfigTab/index.ts, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/EditLibraryTabs.test.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/EditLibraryTabs.tsx, apps/admin/src/components/trees/EditTree/EditTree.test.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/CustomConfigTab/CustomConfigTab.test.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/CustomConfigTab/index.ts, apps/admin/src/components/trees/EditTree/EditTreeTabs/EditTreeTabs.test.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/EditTreeTabs.tsx, apps/admin/src/components/versionProfiles/EditVersionProfile/EditVersionProfile.test.tsx, apps/core/src/_types/config.ts, apps/core/src/infra/attribute/__snapshots__/attributeRepo.spec.ts.snap, apps/core/src/infra/attribute/attributeRepo.ts, apps/core/src/infra/library/__snapshots__/libraryRepo.spec.ts.snap, apps/core/src/infra/library/libraryRepo.ts
=> fix: custom config 

apps/core/src/domain/permission/_types.ts, apps/core/src/domain/permission/helpers/defaultPermission.ts, apps/core/src/domain/permission/helpers/permissionByUserGroups.ts, apps/core/src/domain/permission/helpers/treeBasedPermissions.ts
=> fix(core): getInheritedTreeBasedPermission

apps/core/src/__tests__/mockers/amqp.ts, apps/core/src/__tests__/mockers/logger.ts
=> Tests: add new files to mock functions such as logger, amqp, etc

apps/core/config/default.js, apps/core/config/test.js, apps/core/src/__tests__/e2e/api/globalSetup.ts, apps/core/src/_types/config.ts, apps/core/src/config.ts, apps/core/src/depsManager.ts, apps/core/src/index.ts, apps/core/src/pluginsLoader.ts
=> feature(core): handle multiple plugins path in config

apps/core/src/infra/db/dbUtils.spec.ts, apps/core/src/infra/db/dbUtils.ts
=> fix(core): Use config plugins path on plugins db migration

apps/core/src/index.ts, libs/utils/src/types/events.ts
=> fix loading plugins in server mode

apps/core/src/index.ts
=> fix: init plugins order

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/_gqlTypes/GET_GLOBAL_SETTINGS.ts, apps/admin/src/_gqlTypes/globalTypes.ts, apps/admin/src/components/general/General/General.test.tsx, apps/admin/src/components/general/General/General.tsx, apps/admin/src/components/general/General/GeneralCustomConfigTab/GeneralCustomConfigTab.test.tsx, apps/admin/src/components/general/General/GeneralCustomConfigTab/GeneralCustomConfigTab.tsx, apps/admin/src/components/general/General/GeneralCustomConfigTab/index.ts, apps/admin/src/components/general/General/GeneralCustomizationTab/GeneralCustomizationTab.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/queries/globalSettings/getGlobalSettingsQuery.ts, apps/admin/src/queries/globalSettings/saveGlobalSettingsMutation.ts, apps/core/src/_types/globalSettings.ts, apps/core/src/app/core/globalSettingsApp.ts, apps/core/src/domain/globalSettings/globalSettingsDomain.ts, apps/core/src/infra/globalSettings/__snapshots__/globalSettingsRepo.spec.ts.snap, apps/core/src/infra/globalSettings/globalSettingsRepo.ts
=> feat(admin): add custom config in General tab

apps/core/src/_types/globalSettings.ts
=> feat: sdo improve typing custom config

apps/core/src/domain/actions/excelCalculationAction.ts
=> fix leavc-61: Fix for excel raw payload

apps/admin/src/_gqlTypes/SAVE_GLOBAL_SETTINGS.ts, apps/admin/src/components/applications/EditApplication/EditApplicationTabs/SettingsTab/SettingsTab.tsx, apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/general/General/GeneralCustomConfigTab/GeneralCustomConfigTab.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/CustomConfigTab/CustomConfigTab.tsx, apps/admin/src/components/trees/EditTree/EditTreeTabs/CustomConfigTab/CustomConfigTab.tsx, apps/core/src/app/core/globalSettingsApp.ts, apps/core/src/infra/globalSettings/globalSettingsRepo.ts
=> fix(core): Custom config fix missing deafultApp

apps/admin/src/components/general/General/GeneralCustomConfigTab/GeneralCustomConfigTab.test.tsx, apps/admin/src/components/general/General/GeneralCustomConfigTab/GeneralCustomConfigTab.tsx
=> fix: custom config data not updated

apps/core/src/__tests__/mocks/cache.ts, apps/core/src/app/core/globalSettingsApp.ts, apps/core/src/domain/globalSettings/globalSettingsDomain.spec.ts, apps/core/src/domain/globalSettings/globalSettingsDomain.ts, apps/core/src/utils/utils.ts
=> feat(core): memoize global settings getter/setter

apps/core/src/domain/record/recordDomain.ts, apps/core/src/domain/value/helpers/canSaveRecordValue.ts, apps/core/src/domain/value/valueDomain.ts
=> fix(core): do not check edit permissions on record creation

apps/core/src/app/auth/authApp.ts, apps/core/src/infra/oidc/oidcClientService.ts
=> fix(core): oidc logout when expired

apps/admin/package.json, apps/admin/public/manifest.json, apps/automate-scan/package.json, apps/core/package.json, apps/data-studio/package.json, apps/data-studio/public/manifest.json, apps/login/package.json, apps/login/public/manifest.json, apps/logs-collector/package.json, apps/portal/package.json, apps/portal/public/manifest.json, apps/preview-generator/package.json, apps/skeleton-app/package.json, apps/sync-scan/package.json, libs/app-root-path/package.json, libs/config-manager/package.json, libs/message-broker/package.json, package.json, test-apps/logs/package.json
=> chore: new leav version

apps/core/src/app/core/formApp/formApp.ts, apps/core/src/domain/form/formDomain.ts
=> fix(core): do not filter readonly attributes on default form

libs/ui/src/components/Explorer/DataView.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/Explorer/Explorer.tsx, libs/ui/src/components/Explorer/_types.ts, libs/ui/src/components/Explorer/usePagination.tsx, libs/ui/src/components/Explorer/useSearchInput.tsx
=> fix(explorer): fix bug when performing text search from page > 1

apps/data-studio/package.json, apps/login/package.json, apps/portal/package.json, apps/skeleton-app/package.json, apps/skeleton-app/src/config/theme/InitTheme.tsx, apps/skeleton-app/src/config/translation/InitTranslation.tsx, apps/skeleton-app/src/config/translation/initI18n.ts, apps/skeleton-app/src/config/translation/utils.ts, apps/skeleton-app/src/config/user/InitUser.tsx, apps/skeleton-app/src/modules/ApplicationRouting/Panel.tsx, apps/skeleton-app/src/modules/ApplicationRouting/WorkspaceAndPanels.tsx, apps/skeleton-app/src/modules/layout/Page.tsx, apps/skeleton-app/src/modules/layout/RootHeader.tsx, apps/skeleton-app/src/modules/switch-language/LanguageSelector.tsx, libs/ui/package.json, libs/ui/src/components/Explorer/TableCell.tsx, libs/ui/src/components/ImportModal/ImportModalConfigStep/ImportModalConfigStep.tsx, yarn.lock
=> feat(skeleton-app): fix bugs + upgrade DS Version

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/_gqlTypes/GET_LIB_BY_ID.ts, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/EditLibraryTabs.test.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/InfosTab/InfosForm/InfosForm.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/InfosTab/InfosTab.tsx, apps/admin/src/queries/libraries/libraryDetailsFragment.ts
```
[Carte d'identité] Permettre la configuration du sous libelle de la CI dans l'administration
*️⃣ Impacted projects : Admin
📖 Ticket: https://aristid.atlassian.net/jira/software/c/projects/AMONT/boards/342?selectedIssue=LEAVC-44
```
=> feat(admin): add sublabel for idcard in admin settings

apps/core/src/_constants/attributes.ts, apps/core/src/domain/form/formDomain.ts
=> feat(core): filter base attributes on default forms

apps/skeleton-app/src/config/user/InitUser.tsx, apps/skeleton-app/src/config/user/__tests__/InitUser.spec.tsx
=> fix(skeleton): inverse condition mistake

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/__mocks__/forms.ts, apps/admin/src/_gqlTypes/GET_FORM.ts, apps/admin/src/_gqlTypes/SAVE_FORM.ts, apps/admin/src/_gqlTypes/globalTypes.ts, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/formBuilderReducer/_fixtures/fixtures.ts, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/InfosTab/InfosForm/InfosForm.tsx, apps/admin/src/queries/forms/formDetailsFragment.ts, apps/core/src/__tests__/mocks/forms.ts, apps/core/src/_types/forms.ts, apps/core/src/app/core/formApp/formApp.ts, apps/core/src/domain/form/formDomain.spec.ts, apps/core/src/domain/form/formDomain.ts, apps/core/src/infra/db/migrations/010-formSidePanel.ts, apps/core/src/infra/form/__snapshots__/formRepo.spec.ts.snap
=> feat:(core,admin): LEAVC-82 add the possibility to disable or update the default side panel form behavior

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/_gqlTypes/globalTypes.ts, apps/admin/src/components/shared/LibraryIcon/LibraryIcon.tsx, apps/core/src/_types/library.ts, apps/core/src/utils/helpers/getLibraryDefaultAttributes.ts, apps/data-studio/src/_gqlTypes/globalTypes.ts, apps/data-studio/src/_gqlTypes/index.ts, apps/data-studio/src/components/Home/LibrariesList/LibraryIcon/LibraryIcon.tsx, libs/ui/src/_gqlTypes/index.ts, libs/ui/src/components/LibraryItemsList/CreateNewRecordButton/CreateNewRecordButton.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json
=> feat: Add join library behavior

apps/admin/src/index.tsx, apps/data-studio/src/index.tsx, libs/ui/src/_tests/testUtils.tsx, libs/ui/src/components/CreateDirectory/CreateDirectory.tsx, libs/ui/src/components/EditLibraryModal/EditLibrary/EditLibraryAttributes/AttributesList/DeleteButton/DeleteButton.tsx, libs/ui/src/components/EditLibraryModal/EditLibrary/EditLibraryAttributes/EditLibraryAttributes.test.tsx, libs/ui/src/components/EditLibraryModal/EditLibraryModal.test.tsx, libs/ui/src/components/EditTreeModal/EditTree/EditTreeInfo/EditTreeInfoForm/TreeLibrariesForm/TreeLibrariesForm.tsx, libs/ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx, libs/ui/src/components/Explorer/Explorer.test.tsx, libs/ui/src/components/LibraryItemsList/CreateNewRecordButton/CreateNewRecordButton.test.tsx, libs/ui/src/components/LibraryItemsList/CreateNewRecordButton/CreateNewRecordButton.tsx, libs/ui/src/components/LibraryItemsList/FiltersPanel/Filter/Filter.tsx, libs/ui/src/components/LibraryItemsList/LibraryItemsListContent/LibraryItemsListContent.test.tsx, libs/ui/src/components/LibraryItemsList/shared/DeactivateRecordBtn/DeactivateRecordBtn.test.tsx, libs/ui/src/components/LibraryItemsList/shared/DeactivateRecordBtn/DeactivateRecordBtn.tsx, libs/ui/src/components/RecordEdition/EditRecord/EditRecord.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/hooks/useRunActionsListAndFormatOnValue.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/ValuesList/DSListSelect.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/TreeField/TreeField.test.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.integration.test.tsx, libs/ui/src/components/RecordEdition/EditRecordSidebar/AttributeSummary/useAttributeInformations.test.ts, libs/ui/src/components/RecordEdition/EditRecordSidebar/RecordSummary/RecordInformations/useRecordInformations.test.ts, libs/ui/src/components/SimpleErrorBoundary/SimpleErrorBoundary.test.tsx, libs/ui/src/components/SimpleErrorBoundary/SimpleErrorBoundary.tsx, libs/ui/src/components/UploadFiles/UploadFiles.test.tsx, libs/ui/src/components/UploadFiles/UploadFiles.tsx, libs/ui/src/hooks/useRefreshFieldValues/useRefreshFieldValues.test.tsx, uiResult.txt
=> fix leav/ui tests warnings

libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.integration.test.tsx, libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx
=> fix: enableSidebar default value

apps/skeleton-app/src/modules/ApplicationRouting/PanelContent.module.css, apps/skeleton-app/src/modules/ApplicationRouting/PanelContent.tsx, apps/skeleton-app/src/modules/ApplicationRouting/PanelCustom.module.css, apps/skeleton-app/src/modules/ApplicationRouting/PanelCustom.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/PanelsNavigationMenu.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/panelsNavigationMenu.module.css, apps/skeleton-app/src/modules/display-sidePanel/SidePanel.tsx, libs/ui/src/hooks/index.ts, libs/ui/src/hooks/useIFrameMessenger/messageHandlers.tsx, libs/ui/src/hooks/useIFrameMessenger/types.ts, libs/ui/src/hooks/useIFrameMessenger/useIFrameMessenger.tsx
=> add iframes communication

apps/skeleton-app/jest.config.js, apps/skeleton-app/package.json, apps/skeleton-app/src/__generated__/index.ts, apps/skeleton-app/src/modules/ApplicationRouting/PanelIdCard.tsx, apps/skeleton-app/src/modules/ApplicationRouting/PanelIdCardSkeleton.tsx, apps/skeleton-app/src/modules/ApplicationRouting/__tests__/useApplicationMatching.spec.ts, apps/skeleton-app/src/modules/ApplicationRouting/guards/__tests__/RedirectToFirstPanelOnHome.spec.tsx, apps/skeleton-app/src/modules/ApplicationRouting/guards/__tests__/RedirectToFirstPanelOnUnknownOne.spec.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/PanelsNavigationMenu.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/WorkspacesNavigationMenu.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/__tests__/PanelsNavigationMenu.spec.tsx, apps/skeleton-app/src/modules/ApplicationRouting/navigation-menu/__tests__/WorkspacesNavigationMenu.spec.tsx, apps/skeleton-app/src/modules/ApplicationRouting/recordIdCard.graphql, apps/skeleton-app/src/modules/ApplicationRouting/types.ts, yarn.lock
=> feat(skeleton): add and use localized name for panels

apps/admin/public/locales/en/translations.json, apps/admin/public/locales/fr/translations.json, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/FormsTab/EditForm/EditFormTabs/ContentTab/uiElements/index.tsx, apps/admin/src/components/libraries/EditLibrary/EditLibraryTabs/InfosTab/InfosForm/InfosForm.tsx, apps/core/src/app/core/libraryApp/libraryApp.ts, libs/ui/src/components/LinkSelect/LinkSelect.test.tsx, libs/ui/src/components/LinkSelect/LinkSelect.tsx, libs/ui/src/components/LinkSelect/index.ts, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.test.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx, libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/link-record-in-edition/useLinkRecordsInEdition.tsx, libs/ui/src/locales/en/shared.json, libs/ui/src/locales/fr/shared.json, libs/utils/src/types/forms.ts
=> feat(LEAV): link selection

libs/ui/src/components/RecordEdition/EditRecordModal/EditRecordModal.tsx
=> feat(leav/ui): add prop for auto height in edit record modal

apps/skeleton-app/src/modules/ApplicationRouting/PanelContent.module.css
=> fix(skeleton): explorer pagination not showwing in skeleton app
